// orrery-stamp — the shared build-stamp step (spec §10, contracts §4).
//
// Writes the stamp as a module, from git, AT BUILD TIME. The output is
// gitignored on purpose: a stamp describes a build, so a checked-in file that
// someone can hand-edit is not a stamp — it is a claim.
//
// Copy this file into a repo as scripts/gen-stamp.mjs and run it before the
// build. Configure with STAMP_PROJECT (defaults to the package name) and
// STAMP_OUT (defaults to src/stamp.generated.ts).
//
// In CI, GITHUB_SHA / GITHUB_REF_NAME win over local git: a detached CI
// checkout reports a useless branch name otherwise.
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const git = (...args) => execFileSync('git', args, { encoding: 'utf8' }).trim();
const pkg = JSON.parse(
  execFileSync('node', ['-p', 'JSON.stringify(require("./package.json"))'], {
    encoding: 'utf8',
    cwd: process.cwd(),
  }),
);
const out = process.env.STAMP_OUT ?? 'src/stamp.generated.ts';

const stamp = {
  project: process.env.STAMP_PROJECT ?? pkg.name,
  commit: process.env.GITHUB_SHA ?? git('rev-parse', 'HEAD'),
  branch: process.env.GITHUB_REF_NAME ?? git('rev-parse', '--abbrev-ref', 'HEAD'),
  builtAt: new Date().toISOString(),
  version: pkg.version,
};

writeFileSync(out, `// GENERATED by scripts/gen-stamp.mjs — do not edit.\nexport const STAMP = ${JSON.stringify(stamp, null, 2)} as const;\n`);

// Static sites: emit the stamp as a plain asset at the exact path /__meta.
// Astro only prerenders endpoints whose filename carries an extension
// (rss.xml.js -> /rss.xml), so a `src/pages/__meta.ts` route produces no file;
// and a server route is shadowed by Workers Assets, which answers GET before
// the Worker runs. A generated asset sidesteps both. Headers come from
// _headers — the stamp MUST be no-store.
if (process.env.STAMP_JSON_OUT) {
  writeFileSync(process.env.STAMP_JSON_OUT, `${JSON.stringify(stamp, null, 2)}\n`);
}
console.log(`stamp: ${stamp.commit.slice(0, 8)} on ${stamp.branch}`);
